/* Project Euler in Javascript
 * (Specifically Rhino JavaScript-C 1.6 2006-11-19)
 * John Evans <john@jpevans.com>
 *
 * To invoke:
 * "js euler.js"
 */


/* Euler #1
 * Answer: 233168
 *
 * If we list all the natural numbers below 10 that are multiples of 3 or 5,
 * we get 3, 5, 6 and 9. The sum of these multiples is 23.
 *
 * Find the sum of all the multiples of 3 or 5 below 1000.
 */
function euler1() {
    var n = 0;
    for (var i=0; i<1000; i++) {
        if ((i % 3 == 0)  || (i % 5 == 0)) {
            n += i;
        }
    }
    return n;
}

/* Euler #2
 * Answer: 4613732
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * Find the sum of all the even-valued terms in the sequence which do not
 * exceed four million.
 */
function euler2() {
    var a = 1, b = 2, n = 2;
    while (true) {
        var c = a + b;
        if (c >= 4000000) {
            break;
        }
        if (c % 2 == 0) {
            n += c;
        }
        a = b;
        b = c;
    }
    return n;
}


// Euler #3:
// Answer: 6857
//
// The prime factors of 13195 are 5, 7, 13 and 29.
//
// What is the largest prime factor of the number 600851475143 ?

function is_prime(n) {
    for (var i=Math.ceil(Math.sqrt(n)); i>2; i--) {
        if (n % i == 0) {
            return false
        }
    }
    return true;
}

function euler3() {
    const target = 600851475143;
    for (var i=Math.ceil(Math.sqrt(target)); i>2; i--) {
        if ((target % i == 0) && is_prime(i)) {
            return i;
        }
    }
    return -1;
}


// Problem #4
// Answer: 906609
//
// A palindromic number reads the same both ways. The largest
// palindrome made from the product of two 2-digit numbers is 9009 =
// 91 99.
//
// Find the largest palindrome made from the product of two 3-digit
// numbers.

function reverse_string(s) {
    return s.split("").reverse().join("");
}

function is_palindromic_number(n) {
    var s = "" + n;
    return s == reverse_string(s);
}

function euler4() {
    var result = 0;
    for (var i=100; i<1000; i++) {
        for (var j=100; j<1000; j++) {
            var p = i * j;
            if (p > result && is_palindromic_number(p)) {
                result = p;
            }
        }
    }
    return result;
}

// Problem #5
// Answer: 232792560
//
// 2520 is the smallest number that can be divided by each of the
// numbers from 1 to 10 without any remainder.
//
// What is the smallest number that is evenly divisible by all of the
// numbers from 1 to 20?

function lcm(a, b)
{
    for (var i=1;; i++) {
        if ((i % a == 0) && (i % b == 0)) {
            return i;
        }
    }
}

function euler5() {
    var result = lcm(1, 2);
    for (var i=2; i<=20; i++) {
        result = lcm(result, i);
    }
    return result;
}



// "Main"

EULERS = [
    euler1,
    euler2,
    euler3,
    euler4,
    euler5,
];

if (arguments.length > 0) {
    for (index in arguments) {
        var n = arguments[index]
        print(n + ": " + EULERS[n-1]());
    }
} else {
    for (var i=0, len = EULERS.length; i<len; i++) {
        print(i + ": " + EULERS[i]());
    }
}