#!/usr/bin/env perl -w

# Project Euler in Perl
# John Evans <john@jpevans.com>

use Strict;
use POSIX;

# Euler #1
# Answer: 233168
# 
# If we list all the natural numbers below 10 that are multiples of 3 or 5,
# we get 3, 5, 6 and 9. The sum of these multiples is 23.
# 
# Find the sum of all the multiples of 3 or 5 below 1000.

sub euler1
{
    my $n = 0;
    my $i;
    for ($i=1; $i<1000; $i++) {
        if (($i % 3 == 0) || ($i % 5 == 0)) {
            $n += $i;
        }
    }
    $n;
}


# Euler #2
# Answer: 4613732
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# Find the sum of all the even-valued terms in the sequence which do not
# exceed four million.

sub euler2
{
    my $n = 2;
    my $a = 1;
    my $b = 2;
    while (1) {
        my $c = $a + $b;
        if ($c > 4000000) {
            last;
        }
        if ($c % 2 == 0) {
            $n = $n + $c;
        }
        $a = $b;
        $b = $c;
    }
    $n;
}


# Euler #3
# Answer: 6857
#
# The prime factors of 13195 are 5, 7, 13 and 29.
#
# What is the largest prime factor of the number 600851475143 ?

sub is_prime
{
    my $n = $_[0];
    if ($n == 2) {
        return 1;
    }
    my $i;
    for ($i=2; $i <= POSIX::ceil(sqrt($n)); $i++) {
        if ($n % $i == 0) {
            return 0;
        }
    }
    return 1;
}


sub euler3
{
    my $target = 600851475143;
    my $i;

    for ($i=POSIX::ceil(sqrt($target)); $i > 2; $i--) {
        if ($target % $i == 0 && is_prime($i)) {
            return $i;
        }
    }
}


@EULERS = (\&euler1, \&euler2, \&euler3);

if (@ARGV) {
    foreach $arg (@ARGV) {
        $result = eval("euler$arg");
        print("$arg: $result\n")
    }
} else {
    foreach $index (0..$#EULERS) {
        $euler = $EULERS[$index];
        $n = $index + 1;
        print("$n: " . &$euler() . "\n");
    }
}
