#!/usr/bin/env ruby

# Project Euler in Ruby (1.8.5)
# John Evans <john@jpevans.com>


# Euler #1
# Answer: 233168
#
# If we list all the natural numbers below 10 that are multiples of 3 or 5,
# we get 3, 5, 6 and 9. The sum of these multiples is 23.
#
# Find the sum of all the multiples of 3 or 5 below 1000.

def euler1
    (1..999).select { |n| n % 3 == 0 or n % 5 == 0 }.inject(0) { |a,b| a + b }
end


# Euler #2
# Answer: 4613732
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# Find the sum of all the even-valued terms in the sequence which do not
# exceed four million.

def euler2
    n, a, b = 2, 1, 2
    while true do
        c = a + b
        if c > 4000000
            break
        end
        if c % 2 == 0
            n = n + c
        end
        a, b = b, c
    end
    n
end

# Euler #3
# Answer: 6857
#
# The prime factors of 13195 are 5, 7, 13 and 29.
#
# What is the largest prime factor of the number 600851475143 ?

class Fixnum
    def prime?
        if self == 2
            return true
        end
        (2..(Math.sqrt(self).ceil)).each do |possible_factor|
            if self % possible_factor == 0
                return false
            end
        end
        return true
    end
end


def euler3
    target = 600851475143
    Math.sqrt(target).ceil.downto(2) do |n|
        if target % n == 0 and n.prime?
            return n
        end
    end
end

# Problem #4
# Answer: 906609
#
# A palindromic number reads the same both ways. The largest
# palindrome made from the product of two 2-digit numbers is 9009 =
# 91 99.
#
# Find the largest palindrome made from the product of two 3-digit
# numbers.

class Fixnum
    def palindrome?
        "#{self}" == "#{self}".reverse
    end
end


def euler4
    result = 0
    (100..999).each do |a|
        (100..999).each do |b|
            p = a * b
            if p > result and p.palindrome?
                result = p
            end
        end
    end
    result
end


EULERS = [
    euler1,
    euler2,
    euler3,
    euler4
]


if __FILE__ == $0
    if ARGV.length > 0
        for arg in ARGV
            puts "#{arg}: #{eval("euler#{arg}")}"
        end
    else
        EULERS.each_with_index do |euler, index|
            puts "#{index+1}: #{euler}"
        end
    end
end
