C Project Euler in Fortran
C John Evans <john@jpevans.com>

       PROGRAM EULER
           PRINT*, EULER1()
           PRINT*, EULER2()
           STOP
       END


C Euler #1
C Answer: 233168
C
C If we list all the natural numbers below 10 that are multiples of 3 or 5,
C we get 3, 5, 6 and 9. The sum of these multiples is 23.
C
C Find the sum of all the multiples of 3 or 5 below 1000.

       FUNCTION EULER1 ()
           EULER1 = 0

           DO I = 3, 999
              IF (MODULO(I, 3) .EQ. 0 .OR. MODULO(I, 5) .EQ. 0) THEN
                  EULER1 = EULER1  + I
              END IF
           END DO
           RETURN
       END


C Euler #2
C Answer: 4613732
C
C Each new term in the Fibonacci sequence is generated by adding the previous
C two terms. By starting with 1 and 2, the first 10 terms will be:
C
C 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
C
C Find the sum of all the even-valued terms in the sequence which do not
C exceed four million.

       FUNCTION EULER2 ()
           INTEGER LAST
           INTEGER NEXT

           EULER2 = 2
           LAST = 1
           CUR = 2

           DO WHILE (CUR < 4000000)
               NEXT = LAST + CUR
               IF (MODULO(NEXT, 2) .EQ. 0) THEN
                   EULER2 = EULER2 + NEXT
               END IF
               LAST = CUR
               CUR = NEXT
           END DO
           RETURN
       END