#!/usr/bin/env ruby

# Project Euler in Ruby (1.8.5)
# John Evans <john@jpevans.com>


# Euler #1
# Answer: 233168
#
# If we list all the natural numbers below 10 that are multiples of 3 or 5,
# we get 3, 5, 6 and 9. The sum of these multiples is 23.
#
# Find the sum of all the multiples of 3 or 5 below 1000.

def euler1
    (1..999).select { |n| n % 3 == 0 or n % 5 == 0 }.inject(0) { |a,b| a + b }
end


# Euler #2
# Answer: 4613732
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# Find the sum of all the even-valued terms in the sequence which do not
# exceed four million.

def euler2
    n, a, b = 2, 1, 2
    while true do
        c = a + b
        if c > 4000000
            break
        end
        if c % 2 == 0
            n = n + c
        end
        a, b = b, c
    end
    n
end

EULERS = [
    euler1,
    euler2
]


if __FILE__ == $0
    if ARGV.length > 0
        puts "ARGV"
        for arg in ARGV
            puts "#{arg}: #{eval("euler#{arg}")}"
        end
    else
        EULERS.each_with_index do |euler, index|
            puts "#{index+1}: #{euler}"
        end
    end
end
