-module(euler).
-export([euler1/0,euler2/0]).
%,euler2/0]).


% Euler #1
% Answer: 233168
%
% If we list all the natural numbers below 10 that are multiples of 3 or 5,
% we get 3, 5, 6 and 9. The sum of these multiples is 23.
%
% Find the sum of all the multiples of 3 or 5 below 1000.
e1acc(N, MAX, ACC) when N >= MAX -> ACC;
e1acc(N, MAX, ACC) when (N rem 3 == 0) or (N rem 5 == 0) ->
    e1acc(N + 1, MAX, ACC + N);
e1acc(N, MAX, ACC) -> e1acc(N + 1, MAX, ACC).

euler1() -> e1acc(1, 1000, 0).


% Euler #2
% Answer: 4613732
%
% Each new term in the Fibonacci sequence is generated by adding the previous
% two terms. By starting with 1 and 2, the first 10 terms will be:
%
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%
% Find the sum of all the even-valued terms in the sequence which do not
% exceed four million.

e2_next_acc(ACC, C) when C rem 2 == 0 -> ACC + C;
e2_next_acc(ACC, _) -> ACC.

e2acc(_, B, ACC) when B > 4000000 -> ACC;
e2acc(A, B, ACC) ->
    C = A + B,
    e2acc(B, C, e2_next_acc(ACC, C)).

euler2() -> e2acc(1, 2, 2).
